In [1]:
# Print the numpy version and the configuration 
import numpy as np
print(np.__version__)
np.show_config()

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [2]:
#Create a null vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#How to find the memory size of any array
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [4]:
#Create a null vector of size 10 but the fifth value which is 1
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
# Create a vector with values ranging from 10 to 49
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# Reverse a vector
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [8]:
# Create a 3x3 matrix with values ranging from 0 to 8
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [9]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [10]:
# Create a 3x3 identity matrix 
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# reate a 3x3x3 array with random values 
Z = np.random.random((3,3,3))
print(Z)

[[[0.45972494 0.09279871 0.95369567]
  [0.13311141 0.37600823 0.06276282]
  [0.52589312 0.85143075 0.82566247]]

 [[0.43493795 0.65306083 0.18576601]
  [0.90263731 0.77203835 0.46739383]
  [0.65525598 0.25968969 0.983285  ]]

 [[0.58185055 0.81077093 0.97919572]
  [0.67791096 0.84202589 0.85277397]
  [0.32883627 0.40906571 0.66258955]]]


In [12]:
 # Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.028346133524138728 0.9970213216330153


In [13]:
#  Create a random vector of size 30 and find the mean value
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5300006862509224


In [14]:
# How to swap two rows of an array
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [15]:
# Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [16]:
#How to extract items that satisfy a given condition from 1D array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]
#> array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [17]:
#  How to replace items that satisfy a condition with another value in numpy array
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
# How to replace items that satisfy a condition without affecting the original array
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [20]:
#  How to reshape an array
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [22]:
#  Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [24]:
# Create a checkerboard 8x8 matrix using the tile function
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
# ultiply a 5x3 matrix by a 3x2 matrix (real matrix product)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [27]:
#  How to round away from zero a float array 
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-8. -8.  4. -9.  9.  1. -4.  6. 10. -9.]


In [28]:
# How to find common values between two arrays
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 3 6]


In [29]:
#  How to get the dates of yesterday, today and tomorrow
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [30]:
# Create a 5x5 matrix with row values ranging from 0 to 4
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [2]:
# Compute the outer product of two vectors.
import numpy as np
rl = np.outer(np.ones((5,)), np.linspace(-2, 2, 5))
rl

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [4]:
# Vector cross-product.
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)


array([-3,  6, -3])

In [6]:
# Standard Set Operations
array1 = np.array([[10, 20, 30], [14, 24, 36]])
array2 = np.array([[20, 40, 50], [24, 34, 46]])
# Find the union of two arrays.
print(np.union1d(array1, array2))

[10 14 20 24 30 34 36 40 46 50]


In [7]:
# Find the intersection of two arrays.
print(np.intersect1d(array1, array2))

[20 24]


In [8]:
# Find the set difference of two arrays.
print(np.setdiff1d(array1, array2))
 

[10 14 30 36]


In [9]:
# NumPy Logical operations for selectively picking values from an array depending on a given condition
thearray = np.array([[10, 20, 30], [14, 24, 36]])
 
print(np.logical_or(thearray < 10, thearray > 15))
print("-" * 30)

[[False  True  True]
 [False  True  True]]
------------------------------


In [10]:
print(np.logical_and(thearray < 10, thearray > 15))
print("-" * 30)

[[False False False]
 [False False False]]
------------------------------


In [11]:
print(np.logical_not(thearray < 20))
print("-" * 30)

[[False  True  True]
 [False  True  True]]
------------------------------


In [12]:
#convert List or Tuple into NumPy array
thelist = [1, 2, 3]
print(type(thelist))  # <class 'list'>
 
array1 = np.array(thelist)
print(type(array1))  # <class 'numpy.ndarray'>
 
 
thetuple = ((1, 2, 3))
print(type(thetuple))  # <class 'tuple'>
 
array2 = np.array(thetuple)
print(type(array2))  # <class 'numpy.ndarray'>
 
array3 = np.array([thetuple, thelist, array1])
print(array3)

<class 'list'>
<class 'numpy.ndarray'>
<class 'tuple'>
<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
# create NumPy arrays with linspace()
array1d = np.linspace(1, 12, 2)
print(array1d)
 
array1d = np.linspace(1, 12, 4)
print(array1d)
 
array2d = np.linspace(1, 12, 12).reshape(4, 3)
print(array2d)

[ 1. 12.]
[ 1.          4.66666667  8.33333333 12.        ]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [14]:
# logspace array
thearray = np.logspace(5, 10, num=10, base=10000000.0, dtype=float)
print(thearray)


[1.00000000e+35 7.74263683e+38 5.99484250e+42 4.64158883e+46
 3.59381366e+50 2.78255940e+54 2.15443469e+58 1.66810054e+62
 1.29154967e+66 1.00000000e+70]


In [15]:
# The resize() method modifies existing shape and array itself.
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(3, 3)
print(thearray)

[1 2 3 4]
----------
[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [16]:
# Full array example
array1d = np.full((3), 2)
print(array1d)
 
array2d = np.full((2, 4), 3)
print(array2d)


[2 2 2]
[[3 3 3 3]
 [3 3 3 3]]


In [17]:
# NumPy Indexing 
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d[0])   # Get first value
print(array1d[-1])  # Get last value
print(array1d[3])   # Get 4th value from first
print(array1d[-5])  # Get 5th value from last
 
# Get multiple values
print(array1d[[0, -1]])
 
print("-" * 10)
 
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)
print("-" * 10)
 
print(array2d[0, 0])   # Get first row first col
print(array2d[0, 1])   # Get first row second col
print(array2d[0, 2])   # Get first row third col
 
print(array2d[0, 1])   # Get first row second col 
print(array2d[1, 1])   # Get second row second col
print(array2d[2, 1])   # Get third row second col

1
6
4
2
[1 6]
----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
1
2
3
2
5
8


In [18]:
# Indexing in Multidimensional array
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3d)
 
print(array3d[0, 0, 0])
print(array3d[0, 0, 1])
print(array3d[0, 0, 2])
 
print(array3d[0, 1, 0])
print(array3d[0, 1, 1])
print(array3d[0, 1, 2])
 
print(array3d[1, 0, 0])
print(array3d[1, 0, 1])
print(array3d[1, 0, 2])
 
print(array3d[1, 1, 0])
print(array3d[1, 1, 1])
print(array3d[1, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
# NumPy Single Dimensional Slicing
array1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
print(array1d[4:])  # From index 4 to last index
 
print(array1d[:4])  # From index 0 to 4 index
 
print(array1d[4:7])  # From index 4(included) up to index 7(excluded)
 
print(array1d[:-1])  # Excluded last element
 
print(array1d[:-2])  # Up to second last index(negative index)
 
print(array1d[::-1])  # From last to first in reverse order(negative step)
 
print(array1d[::-2])  # All odd numbers in reversed order
 
print(array1d[-2::-2])  # All even numbers in reversed order
 
print(array1d[::])  # All elements

[4 5 6 7 8 9]
[0 1 2 3]
[4 5 6]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]
[8 6 4 2 0]
[0 1 2 3 4 5 6 7 8 9]


In [20]:
# Flips the order of the axes of an NumPy Array
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)
 
print("-" * 10)
 
# Permute the dimensions of an array.
arrayT = np.transpose(array2d)
print(arrayT)
 
print("-" * 10)
 
# Flip array in the left/right direction.
arrayFlr = np.fliplr(array2d)
print(arrayFlr)
 
print("-" * 10)
 
# Flip array in the up/down direction.
arrayFud = np.flipud(array2d)
print(arrayFud)
 
print("-" * 10)
 
# Rotate an array by 90 degrees in the plane specified by axes.
arrayRot90 = np.rot90(array2d)
print(arrayRot90)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 4 7]
 [2 5 8]
 [3 6 9]]
----------
[[3 2 1]
 [6 5 4]
 [9 8 7]]
----------
[[7 8 9]
 [4 5 6]
 [1 2 3]]
----------
[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [21]:
# oining and Stacking of NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
# Stack arrays in sequence horizontally (column wise).
arrayH = np.hstack((array1, array2))
print(arrayH)
 
print("-" * 10)
 
# Stack arrays in sequence vertically (row wise).
arrayV = np.vstack((array1, array2))
print(arrayV)
 
print("-" * 10)
 
# Stack arrays in sequence depth wise (along third axis).
arrayD = np.dstack((array1, array2))
print(arrayD)
 
print("-" * 10)
 
# Appending arrays after each other, along a given axis.
arrayC = np.concatenate((array1, array2))
print(arrayC)
 
print("-" * 10)
 
# Append values to the end of an array.
arrayA = np.append(array1, array2, axis=0)
print(arrayA)
 
print("-" * 10)
arrayA = np.append(array1, array2, axis=1)
print(arrayA)
 

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [22]:
# Arithmetic Operations with NumPy Array
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
 
print(array1 + array2)
print("-" * 20)
 
print(array1 - array2)
print("-" * 20)
 
print(array1 * array2)
print("-" * 20)
 
print(array2 / array1)
print("-" * 40)
 
print(array1 ** array2)
print("-" * 40)

[[ 8 10 12]
 [14 16 18]]
--------------------
[[-6 -6 -6]
 [-6 -6 -6]]
--------------------
[[ 7 16 27]
 [40 55 72]]
--------------------
[[7.  4.  3. ]
 [2.5 2.2 2. ]]
----------------------------------------
[[          1         256       19683]
 [    1048576    48828125 -2118184960]]
----------------------------------------


In [23]:
# Scalar Arithmetic Operations on NumPy Array
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print(array1 + 2)
print("-" * 20)
 
print(array1 - 5)
print("-" * 20)
 
print(array1 * 2)
print("-" * 20)
 
print(array1 / 5)
print("-" * 20)
 
print(array1 ** 2)
print("-" * 20)

[[12 22 32]
 [42 52 62]]
--------------------
[[ 5 15 25]
 [35 45 55]]
--------------------
[[ 20  40  60]
 [ 80 100 120]]
--------------------
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
--------------------
[[ 100  400  900]
 [1600 2500 3600]]
--------------------
